'use client'
import { ReactNode } from 'react'
import Script from 'next/script'
import AppContext from './appContext'
import { theme } from './globals/theme'

// components
import Header from '../components/header/header'
import Footer from '../components/footer/footer'
// assets
// styles
import 'normalize.css/normalize.css'
import './globals/globals.scss'

type Props = {
  children?: ReactNode
  title?: string
}

export default function RootLayout({ children, title = 'ONBEGRENSD' }: Props) {
  return (
    <html lang="nl">
      <head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" type="image/png" href="/favicon-16x16.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
<link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300&family=Space+Grotesk:wght@300&display=swap" rel="stylesheet" /> 
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.css"
        />
      </head>
      <body>
        <AppContext.Provider value={theme}>
          <Header />
          <main>{children}</main>
          <Footer />
        </AppContext.Provider>
        <Script src="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.js" />
        <div
          hidden
          id="snipcart"
          data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}
        ></div>
      </body>
    </html>
  )
}
