'use client'
import { useState, createContext, ReactNode } from 'react'
import AppContext from './appContext'
// import Header from '../components/header/header'
import { theme } from '../components/theme'

import './globals.scss'

type Props = {
  children?: ReactNode
  title?: string
}

export default function RootLayout({ children, title = 'ONBEGRENSD' }: Props) {
  return (
    <html lang="nl">
      <head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <AppContext.Provider value={theme}>
          {/* <Header /> */}
          <main>{children}</main>
        </AppContext.Provider>
      </body>
    </html>
  )
}
