'use client'
import { ReactNode } from 'react'
import Script from 'next/script'
import { Space_Grotesk, Rajdhani } from '@next/font/google'
import AppContext from './appContext'
import { theme } from './globals/theme'

// components
import Header from '../components/header/header'
// assets
// styles
import 'normalize.css/normalize.css'
import './globals/globals.scss'

type Props = {
  children?: ReactNode
  title?: string
}

const space_Grotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: '400',
})

const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: '300',
})

export default function RootLayout({ children, title = 'ONBEGRENSD' }: Props) {
  return (
    <html
      lang="nl"
      className={`${space_Grotesk.className} ${rajdhani.className}`}
    >
      <head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" type="image/png" href="/favicon-16x16.png" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.css"
        />
      </head>
      <body>
        <AppContext.Provider value={theme}>
          <Header />
          <main>{children}</main>
        </AppContext.Provider>
        <Script src="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.js" />
        <div
          hidden
          id="snipcart"
          data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}
        ></div>
      </body>
    </html>
  )
}
